image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - pip install tox
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

test:
  script:
  - tox
