[tool.poetry]
name = "lute"
version = "0.1.0"
description = "Next iteration of our NLU module"
authors = []
build = "cyext.py"

[tool.poetry.dependencies]
python = "^3.5"
attr = "^0.3.1"
pydash = "^4.6"
networkx = "^2.1"
yamraz = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
Cython = "^0.28.4"

[[tool.poetry.source]]
name = "cheeseshop"
url = "https://cheeseshop.vernacular.ai"
